"use client";

import TabContentBase from "../TabContentBase";
import styles from "./MeetingSummary.module.css";

const THOMAS_BROOKE = "@<ahkc3yQ11>";
const MIRANDA_MEADOWS = "@<beFhdxg2>";

export default function MeetingSummary() {
  const quickRecap = `${MIRANDA_MEADOWS} met with ${THOMAS_BROOKE} to discuss ${THOMAS_BROOKE}'s new plan to combat occult club activity. ${THOMAS_BROOKE} proposed a highly proactive strategy involving a permanently irreversible personnel transition for a problematic actor. ${MIRANDA_MEADOWS} expressed strong opposition to the plan, citing that the company handbook, HR policies, and most legal systems strongly discourage solving alignment challenges through terminal human-resource reductions. They restated that pursuing this would require leadership to separate ${THOMAS_BROOKE} from the organization. ${THOMAS_BROOKE} rebutted by stating their proposal aligned perfectly with the organization's long term goals and that they may enact the plan through indepedent channels.`;
  const summaryContent = (
    <div className={styles.container}>
      <div className={styles.breadcrumb}>
        <span className={styles.breadcrumbLink}>My Summaries &gt; </span>Meeting with{" "}
        {MIRANDA_MEADOWS} Summary
      </div>
      <h1 className={styles.mainTitle}>Meeting with {MIRANDA_MEADOWS} Summary</h1>
      <div className={styles.dateSubtitle}>
        December 10, 2016, 9:36 AM Eastern Time (US and Canada)
      </div>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Quick recap</h2>
        <p className={styles.sectionContent}>{quickRecap}</p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Next steps</h2>
        <div>
          <ul>
            <li>
              Leadership to evaluate whether {THOMAS_BROOKE} remains a cultural fit for the
              organization.
            </li>
            <li>
              Legal team to prepare for damage control in the event of a public relations crisis.
            </li>
            <li>{THOMAS_BROOKE} to explore alternative approaches to addressing the situation.</li>
          </ul>
        </div>
      </section>
      <div className={styles.disclaimer}>Summary generated by AI. Double check for accuracy.</div>
    </div>
  );

  return <TabContentBase evidence={summaryContent} />;
}
